// Word bank organized by category
// Each word has a vague hint for the imposter

const WORDS = {
  "Animals": [
    { word: "Tiger", hint: "Feared and admired in equal measure" },
    { word: "Penguin", hint: "Overdressed for the climate" },
    { word: "Dolphin", hint: "Smarter than it lets on" },
    { word: "Eagle", hint: "Looking down on everything" },
    { word: "Elephant", hint: "Never forgets, never rushes" },
    { word: "Chameleon", hint: "Hard to pin down" },
    { word: "Octopus", hint: "Arms spread in every direction" },
    { word: "Kangaroo", hint: "Built for movement" },
    { word: "Giraffe", hint: "Always looking over others" },
    { word: "Parrot", hint: "Words that aren't its own" },
    { word: "Shark", hint: "Everyone clears the way" },
    { word: "Butterfly", hint: "A second chance at life" },
    { word: "Panda", hint: "Rare and universally loved" },
    { word: "Flamingo", hint: "One foot in, one foot out" },
    { word: "Sloth", hint: "Time means nothing here" },
    { word: "Cheetah", hint: "Gone before you blink" },
    { word: "Jellyfish", hint: "No brain, no problem" },
    { word: "Peacock", hint: "Puts on quite a show" },
    { word: "Gorilla", hint: "Commands respect without words" },
    { word: "Seahorse", hint: "Gentler than expected" },
    { word: "Koala", hint: "Always half asleep" },
    { word: "Bat", hint: "Only out after dark" },
    { word: "Crocodile", hint: "Still as a statue, deadly as a trap" },
    { word: "Wolf", hint: "Never alone by choice" },
    { word: "Owl", hint: "Turns heads effortlessly" },
    { word: "Hedgehog", hint: "Better to admire from a distance" },
    { word: "Whale", hint: "Biggest voice in the room" },
    { word: "Fox", hint: "Always two steps ahead" },
    { word: "Turtle", hint: "Takes the long way home" },
    { word: "Hamster", hint: "Goes nowhere fast" }
  ],

  "Food & Drinks": [
    { word: "Pizza", hint: "Best when shared" },
    { word: "Sushi", hint: "Art you're allowed to eat" },
    { word: "Tacos", hint: "Messy but worth it" },
    { word: "Ice Cream", hint: "Better when the mood is right" },
    { word: "Pancakes", hint: "Stacked high and patient" },
    { word: "Chocolate", hint: "Forbidden comfort" },
    { word: "Avocado", hint: "Trendy and divisive" },
    { word: "Popcorn", hint: "Best enjoyed in the dark" },
    { word: "Pasta", hint: "Simple perfection" },
    { word: "Burger", hint: "Stacked and satisfying" },
    { word: "Watermelon", hint: "Summer in a single bite" },
    { word: "Coffee", hint: "The daily ritual millions rely on" },
    { word: "Nachos", hint: "Better when shared" },
    { word: "Donut", hint: "Complete but missing something" },
    { word: "Ramen", hint: "Warmth in a bowl" },
    { word: "Smoothie", hint: "Liquified good intentions" },
    { word: "Pretzel", hint: "Twisted tradition" },
    { word: "Waffles", hint: "Grids of indulgence" },
    { word: "Mango", hint: "Sweetness with attitude" },
    { word: "Steak", hint: "Patience rewarded with heat" },
    { word: "Lemonade", hint: "Sour made sweet" },
    { word: "Mac and Cheese", hint: "Nostalgia in a bowl" },
    { word: "Boba Tea", hint: "Something surprising at the bottom" },
    { word: "French Fries", hint: "Salt and satisfaction" },
    { word: "Milkshake", hint: "Thick and unhurried" },
    { word: "Croissant", hint: "Layers of patience" },
    { word: "Hot Dog", hint: "The crowd pleaser" },
    { word: "Cheesecake", hint: "Dense and indulgent" },
    { word: "Fried Chicken", hint: "Golden outside, tender inside" },
    { word: "Cereal", hint: "Floating in white" }
  ],

  "Places": [
    { word: "Beach", hint: "Between two worlds" },
    { word: "Library", hint: "Where silence speaks loudest" },
    { word: "Hospital", hint: "Hope and helplessness, side by side" },
    { word: "Airport", hint: "Between here and somewhere else" },
    { word: "Casino", hint: "Fortune favors no one for long" },
    { word: "Museum", hint: "Yesterday on display" },
    { word: "Gym", hint: "Pain you choose and pay for" },
    { word: "Mall", hint: "Temptation on every floor" },
    { word: "Theme Park", hint: "Lines and screams" },
    { word: "Movie Theater", hint: "Darkness by choice" },
    { word: "Restaurant", hint: "Someone else does the work" },
    { word: "Camping", hint: "Back to basics, by choice" },
    { word: "School", hint: "Required and resented" },
    { word: "Zoo", hint: "Wildlife, on your terms" },
    { word: "Stadium", hint: "Thousands with one voice" },
    { word: "Aquarium", hint: "Glass between two worlds" },
    { word: "Cruise Ship", hint: "A city that never docks" },
    { word: "Farm", hint: "Where food begins" },
    { word: "Spa", hint: "Silence and softness, purchased" },
    { word: "Ski Resort", hint: "Cold, fast, and exhilarating" },
    { word: "Bowling Alley", hint: "Heavy aim, hollow result" },
    { word: "Laundromat", hint: "Waiting and spinning" },
    { word: "Barbershop", hint: "Conversation and transformation" },
    { word: "Gas Station", hint: "A necessary interruption" },
    { word: "Cemetery", hint: "Where stories end" },
    { word: "Lighthouse", hint: "Steady in the storm" },
    { word: "Treehouse", hint: "Childhood above the ground" },
    { word: "Rooftop", hint: "Above the chaos" },
    { word: "Subway", hint: "The city moving underground" },
    { word: "Church", hint: "Seeking something higher" }
  ],

  "Jobs & Professions": [
    { word: "Firefighter", hint: "Runs toward what others flee" },
    { word: "Astronaut", hint: "Left Earth behind" },
    { word: "Chef", hint: "Transforms the raw into the remarkable" },
    { word: "Detective", hint: "Questions everything, trusts nothing" },
    { word: "Pilot", hint: "Between ground and sky" },
    { word: "Dentist", hint: "Feared but necessary" },
    { word: "Lifeguard", hint: "Watches without being watched" },
    { word: "DJ", hint: "Reads the room" },
    { word: "Surgeon", hint: "Precision under pressure" },
    { word: "Magician", hint: "Nothing is as it seems" },
    { word: "Plumber", hint: "Works behind the walls" },
    { word: "Veterinarian", hint: "Speaks for those who can't" },
    { word: "Barista", hint: "Powers the morning" },
    { word: "Photographer", hint: "Stops time" },
    { word: "Electrician", hint: "Masters of hidden currents" },
    { word: "Tattoo Artist", hint: "Permanent decisions" },
    { word: "Zookeeper", hint: "Keeper of wild things" },
    { word: "Coach", hint: "Believes before you do" },
    { word: "Librarian", hint: "Knows every story" },
    { word: "Mailman", hint: "Connects strangers daily" },
    { word: "Archaeologist", hint: "The past, unearthed" },
    { word: "Weatherman", hint: "Often wrong, always confident" },
    { word: "Florist", hint: "Beauty, cut short on purpose" },
    { word: "Bus Driver", hint: "Same route, different passengers" },
    { word: "Clown", hint: "Hiding behind a smile" },
    { word: "Blacksmith", hint: "Bends what others cannot" },
    { word: "Farmer", hint: "Works while others sleep" },
    { word: "Journalist", hint: "Chases the truth" },
    { word: "Mime", hint: "Says everything without words" },
    { word: "Stunt Double", hint: "Takes the fall for others" }
  ],

  "Movies & TV": [
    { word: "Star Wars", hint: "Good, evil, and something in between" },
    { word: "The Lion King", hint: "Power passed through blood" },
    { word: "Harry Potter", hint: "Chosen without consent" },
    { word: "The Office", hint: "Familiar to everyone's pain" },
    { word: "Titanic", hint: "Love meets inevitability" },
    { word: "Stranger Things", hint: "Something lurking below the surface" },
    { word: "Finding Nemo", hint: "Love crosses any distance" },
    { word: "Friends", hint: "Six lives forever intertwined" },
    { word: "Jurassic Park", hint: "Nature refuses control" },
    { word: "Breaking Bad", hint: "A slow, irreversible transformation" },
    { word: "Frozen", hint: "Walls built entirely from within" },
    { word: "The Avengers", hint: "Strength in numbers" },
    { word: "Shrek", hint: "Layers, not looks" },
    { word: "Game of Thrones", hint: "Power corrupts everyone it touches" },
    { word: "Toy Story", hint: "Loyalty to the very end" },
    { word: "Batman", hint: "Justice without rules" },
    { word: "SpongeBob", hint: "Optimism in an unlikely place" },
    { word: "The Matrix", hint: "Question everything you see" },
    { word: "Jaws", hint: "Fear arrives before you see it" },
    { word: "Indiana Jones", hint: "History is dangerous" },
    { word: "Squid Game", hint: "Desperation given a set of rules" },
    { word: "Ghostbusters", hint: "Catching what no one believes in" },
    { word: "The Simpsons", hint: "Same family, endless trouble" },
    { word: "Rocky", hint: "Rising from nothing" },
    { word: "Up", hint: "Grief turned into adventure" },
    { word: "Twilight", hint: "Forbidden attraction" },
    { word: "Scooby-Doo", hint: "Always a human behind the mask" },
    { word: "Jeopardy", hint: "Knowledge with a twist" },
    { word: "Willy Wonka", hint: "Invitation to the impossible" },
    { word: "The Walking Dead", hint: "What makes us human?" }
  ],

  "Sports & Hobbies": [
    { word: "Basketball", hint: "Up and through" },
    { word: "Surfing", hint: "At the mercy of nature" },
    { word: "Chess", hint: "Thinking ten moves ahead" },
    { word: "Yoga", hint: "Stillness through movement" },
    { word: "Skateboarding", hint: "Concrete creativity" },
    { word: "Fishing", hint: "Patience rewarded occasionally" },
    { word: "Boxing", hint: "Controlled aggression" },
    { word: "Photography", hint: "Freezing a single moment" },
    { word: "Rock Climbing", hint: "Trust your grip" },
    { word: "Karate", hint: "Discipline before power" },
    { word: "Bowling", hint: "Set them up to knock them down" },
    { word: "Golf", hint: "Fewer strokes, more status" },
    { word: "Paintball", hint: "Friendly fire" },
    { word: "Archery", hint: "Still and precise" },
    { word: "Tennis", hint: "Back and forth, endlessly" },
    { word: "Snowboarding", hint: "Sideways down a mountain" },
    { word: "Poker", hint: "Who blinks first" },
    { word: "Scuba Diving", hint: "Breathing where you shouldn't" },
    { word: "Volleyball", hint: "Keep it off the ground" },
    { word: "Ice Skating", hint: "Grace meets friction" },
    { word: "Pottery", hint: "Centered by hands" },
    { word: "Fencing", hint: "Touch without lasting harm" },
    { word: "Darts", hint: "Numbers and precision" },
    { word: "Table Tennis", hint: "Speed in a small space" },
    { word: "Hiking", hint: "The destination isn't the point" },
    { word: "Wrestling", hint: "Controlled falling" },
    { word: "Gardening", hint: "Tending to things that grow slowly" },
    { word: "Horse Riding", hint: "Partnership in motion" },
    { word: "Swimming", hint: "Fighting your natural state" },
    { word: "Magic Tricks", hint: "See it, then doubt it" }
  ],

  "Brands & Products": [
    { word: "Nike", hint: "Performance made visible" },
    { word: "iPhone", hint: "In every pocket" },
    { word: "Netflix", hint: "The reason plans get cancelled" },
    { word: "Coca-Cola", hint: "Red and instantly familiar" },
    { word: "LEGO", hint: "Build it, break it, build again" },
    { word: "McDonald's", hint: "Consistent wherever you go" },
    { word: "Tesla", hint: "Quiet and fast" },
    { word: "Disney", hint: "Childhood wrapped in a logo" },
    { word: "Amazon", hint: "Arrives without leaving home" },
    { word: "PlayStation", hint: "Hours disappear here" },
    { word: "Google", hint: "The first stop for everything" },
    { word: "Starbucks", hint: "Your name spelled wrong" },
    { word: "Instagram", hint: "Best angle, best light" },
    { word: "IKEA", hint: "Assembly required" },
    { word: "Uber", hint: "A stranger takes you somewhere" },
    { word: "YouTube", hint: "Rabbit holes with no end" },
    { word: "Nintendo", hint: "Joy in a handheld" },
    { word: "Spotify", hint: "Your mood, catalogued" },
    { word: "Oreo", hint: "A ritual disguised as a cookie" },
    { word: "TikTok", hint: "Ten seconds at a time" },
    { word: "Airbnb", hint: "Someone else's home, temporarily" },
    { word: "Red Bull", hint: "Claims to give you something" },
    { word: "Adidas", hint: "Three is enough" },
    { word: "Minecraft", hint: "Build your own rules" },
    { word: "Doritos", hint: "Loud in every way" },
    { word: "Monopoly", hint: "Ends in argument" },
    { word: "Kleenex", hint: "So common it became the name" },
    { word: "Gatorade", hint: "Replenish the loss" },
    { word: "Hot Wheels", hint: "Speed shrunk down" },
    { word: "Nutella", hint: "Spread on everything" }
  ],

  "Everyday Things": [
    { word: "Umbrella", hint: "Useless when you need it most" },
    { word: "Microwave", hint: "Fast, but not the same" },
    { word: "Sunglasses", hint: "Hiding in plain sight" },
    { word: "Alarm Clock", hint: "Unwelcome but necessary" },
    { word: "Backpack", hint: "Everything you carry with you" },
    { word: "Elevator", hint: "Awkward silence included" },
    { word: "Remote Control", hint: "Power with a button" },
    { word: "Toothbrush", hint: "The start and end of every day" },
    { word: "Pillow", hint: "Where thoughts wander" },
    { word: "Wallet", hint: "Identity in your pocket" },
    { word: "Mirror", hint: "The honest version" },
    { word: "Candle", hint: "Warmth through sacrifice" },
    { word: "Ladder", hint: "Bridge between levels" },
    { word: "Headphones", hint: "The world, filtered" },
    { word: "Battery", hint: "Hidden energy" },
    { word: "Scissors", hint: "What cannot be undone" },
    { word: "Doorbell", hint: "A small announcement" },
    { word: "Trampoline", hint: "Gravity, briefly defeated" },
    { word: "Blender", hint: "Destruction in seconds" },
    { word: "Zipper", hint: "Precision in a line" },
    { word: "Flashlight", hint: "Borrowed light" },
    { word: "Stamp", hint: "Permission to travel" },
    { word: "Hammock", hint: "Between two points, suspended" },
    { word: "Thermos", hint: "Time holds no power here" },
    { word: "Magnifying Glass", hint: "Things aren't as small as they seem" },
    { word: "Compass", hint: "Always honest about direction" },
    { word: "Lunchbox", hint: "Midday anticipation" },
    { word: "Suitcase", hint: "Ready to leave" },
    { word: "Rubber Duck", hint: "Squeaky and cheerful" },
    { word: "Post-it Note", hint: "Forgotten, then found at the right moment" }
  ]
};

module.exports = WORDS;
