// Word bank organized by category
// Each word has a vague hint for the imposter

const WORDS = {
  "Animals": [
    { word: "Tiger", hint: "Feared and admired in equal measure" },
    { word: "Penguin", hint: "Overdressed for the climate" },
    { word: "Dolphin", hint: "Smarter than it lets on" },
    { word: "Eagle", hint: "Looking down on everything" },
    { word: "Elephant", hint: "Never forgets, never rushes" },
    { word: "Chameleon", hint: "Hard to pin down" },
    { word: "Octopus", hint: "Arms spread in every direction" },
    { word: "Kangaroo", hint: "Built for movement" },
    { word: "Giraffe", hint: "Always looking over others" },
    { word: "Parrot", hint: "Words that aren't its own" },
    { word: "Shark", hint: "Everyone clears the way" },
    { word: "Butterfly", hint: "A second chance at life" },
    { word: "Panda", hint: "Rare and universally loved" },
    { word: "Flamingo", hint: "One foot in, one foot out" },
    { word: "Sloth", hint: "Time means nothing here" },
    { word: "Cheetah", hint: "Gone before you blink" },
    { word: "Jellyfish", hint: "No brain, no problem" },
    { word: "Peacock", hint: "Puts on quite a show" },
    { word: "Gorilla", hint: "Commands respect without words" },
    { word: "Seahorse", hint: "Gentler than expected" },
    { word: "Koala", hint: "Always half asleep" },
    { word: "Bat", hint: "Only out after dark" },
    { word: "Crocodile", hint: "Still as a statue, deadly as a trap" },
    { word: "Wolf", hint: "Never alone by choice" },
    { word: "Owl", hint: "Turns heads effortlessly" },
    { word: "Hedgehog", hint: "Better to admire from a distance" },
    { word: "Whale", hint: "Biggest voice in the room" },
    { word: "Fox", hint: "Always two steps ahead" },
    { word: "Turtle", hint: "Takes the long way home" },
    { word: "Hamster", hint: "Goes nowhere fast" },
    { word: "Moose", hint: "Large and oddly majestic" },
    { word: "Scorpion", hint: "Danger in a small package" },
    { word: "Swan", hint: "Elegance hiding furious effort" },
    { word: "Mole", hint: "Does its best work unseen" },
    { word: "Hummingbird", hint: "Still while moving" },
    { word: "Lobster", hint: "Armored and misunderstood" },
    { word: "Raccoon", hint: "Gets into everything uninvited" },
    { word: "Porcupine", hint: "Closeness comes at a cost" },
    { word: "Starfish", hint: "Rebuilds what was lost" },
    { word: "Hyena", hint: "Finds humor in dark places" },
    { word: "Firefly", hint: "Brief flashes in the dark" },
    { word: "Stingray", hint: "Graceful until provoked" },
    { word: "Camel", hint: "Built to endure the worst" },
    { word: "Ant", hint: "Small but never alone" },
    { word: "Polar Bear", hint: "White coat, cold heart" },
    { word: "Crab", hint: "Never approaches directly" },
    { word: "Pigeon", hint: "Thrives where others won't" },
    { word: "Mongoose", hint: "Fearless against the feared" }
  ],

  "Food & Drinks": [
    { word: "Pizza", hint: "Best when shared" },
    { word: "Sushi", hint: "Art you're allowed to eat" },
    { word: "Tacos", hint: "Messy but worth it" },
    { word: "Ice Cream", hint: "Better when the mood is right" },
    { word: "Pancakes", hint: "Stacked high and patient" },
    { word: "Chocolate", hint: "Forbidden comfort" },
    { word: "Avocado", hint: "Trendy and divisive" },
    { word: "Popcorn", hint: "Best enjoyed in the dark" },
    { word: "Pasta", hint: "Simple perfection" },
    { word: "Burger", hint: "Stacked and satisfying" },
    { word: "Watermelon", hint: "Summer in a single bite" },
    { word: "Coffee", hint: "The daily ritual millions rely on" },
    { word: "Nachos", hint: "Better from the middle" },
    { word: "Donut", hint: "Complete but missing something" },
    { word: "Ramen", hint: "Warmth in a bowl" },
    { word: "Smoothie", hint: "Liquified good intentions" },
    { word: "Pretzel", hint: "Twisted tradition" },
    { word: "Waffles", hint: "Grids of indulgence" },
    { word: "Mango", hint: "Sweetness with attitude" },
    { word: "Steak", hint: "Patience rewarded with heat" },
    { word: "Lemonade", hint: "Sour made sweet" },
    { word: "Mac and Cheese", hint: "Nostalgia in a bowl" },
    { word: "Boba Tea", hint: "Something surprising at the bottom" },
    { word: "French Fries", hint: "Salt and satisfaction" },
    { word: "Milkshake", hint: "Thick and unhurried" },
    { word: "Croissant", hint: "Layers of patience" },
    { word: "Hot Dog", hint: "The crowd pleaser" },
    { word: "Cheesecake", hint: "Dense and indulgent" },
    { word: "Fried Chicken", hint: "Golden outside, tender inside" },
    { word: "Cereal", hint: "Floating in white" },
    { word: "Honey", hint: "Sweetness with a sting behind it" },
    { word: "Soup", hint: "Comfort with no shape of its own" },
    { word: "Bagel", hint: "A hole that makes it whole" },
    { word: "Soda", hint: "Excitement that fades quickly" },
    { word: "Cinnamon Roll", hint: "Wound up tight" },
    { word: "Beef Jerky", hint: "Toughened by time" },
    { word: "Peanut Butter", hint: "Sticks with you" },
    { word: "Garlic Bread", hint: "Nobody says no" },
    { word: "Espresso", hint: "Small but intense" },
    { word: "Cotton Candy", hint: "Disappears on contact" },
    { word: "Guacamole", hint: "Extra always costs more" },
    { word: "Bacon", hint: "Makes everything better" },
    { word: "Champagne", hint: "Saved for the right moment" },
    { word: "Curry", hint: "Layers of warmth that build" },
    { word: "Breadsticks", hint: "Never the star, always welcome" },
    { word: "Kombucha", hint: "Alive and an acquired taste" },
    { word: "Chili", hint: "Low and slow wins" },
    { word: "Energy Drink", hint: "Borrowed time in a can" }
  ],

  "Places": [
    { word: "Beach", hint: "Between two worlds" },
    { word: "Library", hint: "Where silence speaks loudest" },
    { word: "Hospital", hint: "Hope and helplessness, side by side" },
    { word: "Airport", hint: "Between here and somewhere else" },
    { word: "Casino", hint: "Fortune favors no one for long" },
    { word: "Museum", hint: "Yesterday on display" },
    { word: "Gym", hint: "Pain you choose and pay for" },
    { word: "Mall", hint: "Temptation on every floor" },
    { word: "Theme Park", hint: "Lines and screams" },
    { word: "Movie Theater", hint: "Darkness by choice" },
    { word: "Restaurant", hint: "Someone else does the work" },
    { word: "Camping", hint: "Back to basics, by choice" },
    { word: "School", hint: "Required and resented" },
    { word: "Zoo", hint: "Wildlife, on your terms" },
    { word: "Stadium", hint: "Thousands with one voice" },
    { word: "Aquarium", hint: "Glass between two worlds" },
    { word: "Cruise Ship", hint: "A city that never docks" },
    { word: "Farm", hint: "Where food begins" },
    { word: "Spa", hint: "Silence and softness, purchased" },
    { word: "Ski Resort", hint: "Cold, fast, and exhilarating" },
    { word: "Bowling Alley", hint: "Heavy aim, hollow result" },
    { word: "Laundromat", hint: "Waiting and spinning" },
    { word: "Barbershop", hint: "Conversation and transformation" },
    { word: "Gas Station", hint: "A necessary interruption" },
    { word: "Cemetery", hint: "Where stories end" },
    { word: "Lighthouse", hint: "Steady in the storm" },
    { word: "Treehouse", hint: "Childhood above the ground" },
    { word: "Rooftop", hint: "Above the chaos" },
    { word: "Subway", hint: "The city moving underground" },
    { word: "Church", hint: "Seeking something higher" },
    { word: "Parking Garage", hint: "Circling endlessly" },
    { word: "Junkyard", hint: "Value others couldn't see" },
    { word: "Planetarium", hint: "The sky brought indoors" },
    { word: "Courtroom", hint: "Truth under pressure" },
    { word: "Elevator", hint: "Strangers pressed together briefly" },
    { word: "Cabin", hint: "Escape wrapped in wood" },
    { word: "Carnival", hint: "Bright lights hiding rusty bolts" },
    { word: "Dentist Office", hint: "Avoided until unavoidable" },
    { word: "Volcano", hint: "Calm on the surface, rage below" },
    { word: "Prison", hint: "Time moves differently here" },
    { word: "Backstage", hint: "Where the real version lives" },
    { word: "Attic", hint: "Forgotten things piled high" },
    { word: "Waterfall", hint: "Beautiful and deafening" },
    { word: "Food Truck", hint: "Good things from small spaces" },
    { word: "Haunted House", hint: "Fear with a ticket price" },
    { word: "Train Station", hint: "Arrivals and departures, always" },
    { word: "Desert", hint: "Everything stripped to essentials" },
    { word: "Balcony", hint: "Watching without participating" }
  ],

  "Jobs & Professions": [
    { word: "Firefighter", hint: "Runs toward what others flee" },
    { word: "Astronaut", hint: "Left Earth behind" },
    { word: "Chef", hint: "Transforms the raw into the remarkable" },
    { word: "Detective", hint: "Questions everything, trusts nothing" },
    { word: "Pilot", hint: "Between ground and sky" },
    { word: "Dentist", hint: "Feared but necessary" },
    { word: "Lifeguard", hint: "Watches without being watched" },
    { word: "DJ", hint: "Reads the room" },
    { word: "Surgeon", hint: "Precision under pressure" },
    { word: "Magician", hint: "Nothing is as it seems" },
    { word: "Plumber", hint: "Works behind the walls" },
    { word: "Veterinarian", hint: "Speaks for those who can't" },
    { word: "Barista", hint: "Powers the morning" },
    { word: "Photographer", hint: "Stops time" },
    { word: "Electrician", hint: "Masters of hidden currents" },
    { word: "Tattoo Artist", hint: "Permanent decisions" },
    { word: "Zookeeper", hint: "Keeper of wild things" },
    { word: "Coach", hint: "Believes before you do" },
    { word: "Librarian", hint: "Knows every story" },
    { word: "Mailman", hint: "Connects strangers daily" },
    { word: "Archaeologist", hint: "The past, unearthed" },
    { word: "Weatherman", hint: "Often wrong, always confident" },
    { word: "Florist", hint: "Beauty, cut short on purpose" },
    { word: "Bus Driver", hint: "Same route, different passengers" },
    { word: "Clown", hint: "Hiding behind a smile" },
    { word: "Blacksmith", hint: "Bends what others cannot" },
    { word: "Farmer", hint: "Works while others sleep" },
    { word: "Journalist", hint: "Chases the truth" },
    { word: "Mime", hint: "Says everything without words" },
    { word: "Stunt Double", hint: "Takes the fall for others" },
    { word: "Auctioneer", hint: "Words fly faster than thought" },
    { word: "Locksmith", hint: "Opens what was closed" },
    { word: "Translator", hint: "The invisible bridge" },
    { word: "Park Ranger", hint: "Guardian of the untouched" },
    { word: "Sommelier", hint: "Nose knows best" },
    { word: "Cartographer", hint: "Draws the world flat" },
    { word: "Exterminator", hint: "Uninvited guest remover" },
    { word: "Therapist", hint: "Holds space for the heavy" },
    { word: "Air Traffic Controller", hint: "Keeps collisions imaginary" },
    { word: "Glassblower", hint: "Breath becomes solid" },
    { word: "Undertaker", hint: "Last to let you down" },
    { word: "Crossing Guard", hint: "Brief authority at the corner" },
    { word: "Chimney Sweep", hint: "Clean through the dark and narrow" },
    { word: "Food Critic", hint: "Opinions that ruin or make" },
    { word: "Lighthouse Keeper", hint: "Alone with a purpose" },
    { word: "Puppeteer", hint: "Movement from above" },
    { word: "Bouncer", hint: "Decides who belongs" },
    { word: "Midwife", hint: "First hands to hold you" }
  ],

  "Movies & TV": [
    { word: "Star Wars", hint: "Good, evil, and something in between" },
    { word: "The Lion King", hint: "Power passed through blood" },
    { word: "Harry Potter", hint: "Chosen without consent" },
    { word: "The Office", hint: "Familiar to everyone's pain" },
    { word: "Titanic", hint: "Love meets inevitability" },
    { word: "Stranger Things", hint: "Something lurking below the surface" },
    { word: "Finding Nemo", hint: "Love crosses any distance" },
    { word: "Friends", hint: "Six lives forever intertwined" },
    { word: "Jurassic Park", hint: "Nature refuses control" },
    { word: "Breaking Bad", hint: "A slow, irreversible transformation" },
    { word: "Frozen", hint: "Walls built entirely from within" },
    { word: "The Avengers", hint: "Strength in numbers" },
    { word: "Shrek", hint: "Layers, not looks" },
    { word: "Game of Thrones", hint: "Power corrupts everyone it touches" },
    { word: "Toy Story", hint: "Loyalty to the very end" },
    { word: "Batman", hint: "Justice without rules" },
    { word: "SpongeBob", hint: "Optimism in an unlikely place" },
    { word: "The Matrix", hint: "Question everything you see" },
    { word: "Jaws", hint: "Fear arrives before you see it" },
    { word: "Indiana Jones", hint: "History is dangerous" },
    { word: "Squid Game", hint: "Desperation given a set of rules" },
    { word: "Ghostbusters", hint: "Catching what no one believes in" },
    { word: "The Simpsons", hint: "Same family, endless trouble" },
    { word: "Rocky", hint: "Rising from nothing" },
    { word: "Up", hint: "Grief turned into adventure" },
    { word: "Twilight", hint: "Forbidden attraction" },
    { word: "Scooby-Doo", hint: "Always a human behind the mask" },
    { word: "Jeopardy", hint: "Knowledge with a twist" },
    { word: "Willy Wonka", hint: "Invitation to the impossible" },
    { word: "The Walking Dead", hint: "What makes us human?" },
    { word: "Forrest Gump", hint: "Innocence outrunning the world" },
    { word: "The Godfather", hint: "Family above everything, always" },
    { word: "Inception", hint: "Deeper and deeper and deeper" },
    { word: "Grease", hint: "Summer that won't let go" },
    { word: "Black Mirror", hint: "The screen stares back" },
    { word: "Survivor", hint: "Trust is the first casualty" },
    { word: "The Wizard of Oz", hint: "You had it the whole time" },
    { word: "Pokémon", hint: "Gotta have them all" },
    { word: "Wipeout", hint: "Falling is the whole point" },
    { word: "Home Alone", hint: "Small defender, big problems" },
    { word: "The Hunger Games", hint: "Spectacle made from suffering" },
    { word: "Monsters Inc", hint: "Fear is fuel" },
    { word: "E.T.", hint: "Homesick in a strange world" },
    { word: "Back to the Future", hint: "Fixing what hasn't happened yet" },
    { word: "The Truman Show", hint: "Everyone knows but you" },
    { word: "Shark Tank", hint: "Dreams meet cold math" },
    { word: "Groundhog Day", hint: "Same morning, forever" },
    { word: "Zootopia", hint: "Proving everyone wrong about what you are" }
  ],

  "Sports & Hobbies": [
    { word: "Basketball", hint: "Up and through" },
    { word: "Surfing", hint: "At the mercy of nature" },
    { word: "Chess", hint: "Thinking ten moves ahead" },
    { word: "Yoga", hint: "Stillness through movement" },
    { word: "Skateboarding", hint: "Concrete creativity" },
    { word: "Fishing", hint: "Patience rewarded occasionally" },
    { word: "Boxing", hint: "Controlled aggression" },
    { word: "Photography", hint: "Freezing a single moment" },
    { word: "Rock Climbing", hint: "Trust your grip" },
    { word: "Karate", hint: "Discipline before power" },
    { word: "Bowling", hint: "Set them up to knock them down" },
    { word: "Golf", hint: "Fewer strokes, more status" },
    { word: "Paintball", hint: "Friendly fire" },
    { word: "Archery", hint: "Still and precise" },
    { word: "Tennis", hint: "Back and forth, endlessly" },
    { word: "Snowboarding", hint: "Sideways down a mountain" },
    { word: "Poker", hint: "Who blinks first" },
    { word: "Scuba Diving", hint: "Breathing where you shouldn't" },
    { word: "Volleyball", hint: "Keep it off the ground" },
    { word: "Ice Skating", hint: "Grace meets friction" },
    { word: "Pottery", hint: "Centered by hands" },
    { word: "Fencing", hint: "Touch without lasting harm" },
    { word: "Darts", hint: "Numbers and precision" },
    { word: "Table Tennis", hint: "Speed in a small space" },
    { word: "Hiking", hint: "The destination isn't the point" },
    { word: "Wrestling", hint: "Controlled falling" },
    { word: "Gardening", hint: "Tending to things that grow slowly" },
    { word: "Horse Riding", hint: "Partnership in motion" },
    { word: "Swimming", hint: "Fighting your natural state" },
    { word: "Magic Tricks", hint: "See it, then doubt it" },
    { word: "Juggling", hint: "Everything in the air at once" },
    { word: "Origami", hint: "Flat becomes alive" },
    { word: "Arm Wrestling", hint: "Strength across a table" },
    { word: "Birdwatching", hint: "Patience with binoculars" },
    { word: "Dodgeball", hint: "Avoid everything thrown your way" },
    { word: "Kite Flying", hint: "Control at a distance" },
    { word: "Triathlon", hint: "Three punishments in a row" },
    { word: "Crossword", hint: "Letters filling the blanks" },
    { word: "Badminton", hint: "Feathered and fast" },
    { word: "Billiards", hint: "Angles and felt" },
    { word: "Geocaching", hint: "Treasure hidden in plain sight" },
    { word: "Whittling", hint: "Removing to reveal" },
    { word: "Skydiving", hint: "Falling on purpose" },
    { word: "Kayaking", hint: "Alone on moving glass" },
    { word: "Foosball", hint: "Tiny athletes, spinning" },
    { word: "Speed Cubing", hint: "Chaos solved by muscle memory" },
    { word: "Disc Golf", hint: "A walk with consequences" },
    { word: "Tug of War", hint: "One rope, two truths" }
  ],

  "Brands & Products": [
    { word: "Nike", hint: "Performance made visible" },
    { word: "iPhone", hint: "In every pocket" },
    { word: "Netflix", hint: "The reason plans get cancelled" },
    { word: "Coca-Cola", hint: "Red and instantly familiar" },
    { word: "LEGO", hint: "Build it, break it, build again" },
    { word: "McDonald's", hint: "Consistent wherever you go" },
    { word: "Tesla", hint: "Quiet and fast" },
    { word: "Disney", hint: "Childhood wrapped in a logo" },
    { word: "Amazon", hint: "Arrives without leaving home" },
    { word: "PlayStation", hint: "Hours disappear here" },
    { word: "Google", hint: "The first stop for everything" },
    { word: "Starbucks", hint: "Your name spelled wrong" },
    { word: "Instagram", hint: "Best angle, best light" },
    { word: "IKEA", hint: "Assembly required" },
    { word: "Uber", hint: "A stranger takes you somewhere" },
    { word: "YouTube", hint: "Rabbit holes with no end" },
    { word: "Nintendo", hint: "Joy in a handheld" },
    { word: "Spotify", hint: "Your mood, catalogued" },
    { word: "Oreo", hint: "A ritual disguised as a cookie" },
    { word: "TikTok", hint: "Ten seconds at a time" },
    { word: "Airbnb", hint: "Someone else's home, temporarily" },
    { word: "Red Bull", hint: "Claims to give you something" },
    { word: "Adidas", hint: "Three is enough" },
    { word: "Minecraft", hint: "Build your own rules" },
    { word: "Doritos", hint: "Loud in every way" },
    { word: "Monopoly", hint: "Ends in argument" },
    { word: "Kleenex", hint: "So common it became the name" },
    { word: "Gatorade", hint: "Replenish the loss" },
    { word: "Hot Wheels", hint: "Speed shrunk down" },
    { word: "Nutella", hint: "Spread on everything" },
    { word: "Crocs", hint: "Ugly and unstoppable" },
    { word: "Sharpie", hint: "Permanent by name and nature" },
    { word: "Jeep", hint: "Roads are optional" },
    { word: "Costco", hint: "More than you came for" },
    { word: "Band-Aid", hint: "Temporary fix, universal trust" },
    { word: "Sriracha", hint: "Heat with a rooster" },
    { word: "Roomba", hint: "Circles while you're away" },
    { word: "Velcro", hint: "Ripped apart and stuck again" },
    { word: "GoPro", hint: "First-person recklessness" },
    { word: "Chapstick", hint: "Small tube, constant need" },
    { word: "Wikipedia", hint: "Everyone's starting point, no one's source" },
    { word: "Fitbit", hint: "Counting what you'd rather ignore" },
    { word: "Kindle", hint: "A library that fits in a hand" },
    { word: "WD-40", hint: "Fixes the squeak" },
    { word: "Rubik's Cube", hint: "Scrambled order begging for patience" },
    { word: "Tupperware", hint: "Lid always missing" },
    { word: "Nerf", hint: "Violence made soft" },
    { word: "Zamboni", hint: "Erases all the marks" }
  ],

  "Everyday Things": [
    { word: "Umbrella", hint: "Useless when you need it most" },
    { word: "Microwave", hint: "Fast, but not the same" },
    { word: "Sunglasses", hint: "Hiding in plain sight" },
    { word: "Alarm Clock", hint: "Unwelcome but necessary" },
    { word: "Backpack", hint: "Everything you carry with you" },
    { word: "Remote Control", hint: "Power with a button" },
    { word: "Toothbrush", hint: "The start and end of every day" },
    { word: "Pillow", hint: "Where thoughts wander" },
    { word: "Wallet", hint: "Identity in your pocket" },
    { word: "Mirror", hint: "The honest version" },
    { word: "Candle", hint: "Warmth through sacrifice" },
    { word: "Ladder", hint: "Bridge between levels" },
    { word: "Headphones", hint: "The world, filtered" },
    { word: "Battery", hint: "Hidden energy" },
    { word: "Scissors", hint: "What cannot be undone" },
    { word: "Doorbell", hint: "A small announcement" },
    { word: "Trampoline", hint: "Gravity, briefly defeated" },
    { word: "Blender", hint: "Destruction in seconds" },
    { word: "Zipper", hint: "Precision in a line" },
    { word: "Flashlight", hint: "Borrowed light" },
    { word: "Stamp", hint: "Permission to travel" },
    { word: "Hammock", hint: "Between two points, suspended" },
    { word: "Thermos", hint: "Time holds no power here" },
    { word: "Magnifying Glass", hint: "Things aren't as small as they seem" },
    { word: "Compass", hint: "Always honest about direction" },
    { word: "Lunchbox", hint: "Midday anticipation" },
    { word: "Suitcase", hint: "Ready to leave" },
    { word: "Rubber Duck", hint: "Squeaky and cheerful" },
    { word: "Post-it Note", hint: "Forgotten, then found at the right moment" },
    { word: "Clothespin", hint: "Holds things out to dry" },
    { word: "Keychain", hint: "Jingles with every step" },
    { word: "Corkscrew", hint: "Twisting toward celebration" },
    { word: "Duct Tape", hint: "Fixes everything, fixes nothing" },
    { word: "Night Light", hint: "Small comfort in the dark" },
    { word: "Ice Cube", hint: "Disappears doing its job" },
    { word: "Straw", hint: "Empty until used" },
    { word: "Sticky Note", hint: "Clings where you put it" },
    { word: "Extension Cord", hint: "Reaching further than expected" },
    { word: "Paper Clip", hint: "Holds more than it should" },
    { word: "Coaster", hint: "Protects what's beneath" },
    { word: "Bookmark", hint: "Remembers where you stopped" },
    { word: "Tape Measure", hint: "Tells you what you don't want to hear" },
    { word: "Plunger", hint: "Nobody's proud to own one" },
    { word: "Cork", hint: "Keeps things bottled up" },
    { word: "Safety Pin", hint: "Quick fix with a point" },
    { word: "Eraser", hint: "Undoing what was certain" },
    { word: "Paperweight", hint: "Prevents escape" },
    { word: "Welcome Mat", hint: "First impression, stepped on" }
  ],

  "Music & Entertainment": [
    { word: "Guitar", hint: "Six strings, infinite moods" },
    { word: "Karaoke", hint: "Courage borrowed from a screen" },
    { word: "Drums", hint: "The heartbeat underneath" },
    { word: "Piano", hint: "Black and white, yet full of color" },
    { word: "Microphone", hint: "Makes the small voice fill the room" },
    { word: "Concert", hint: "Thousands feeling the same thing" },
    { word: "Vinyl Record", hint: "Warmth trapped in grooves" },
    { word: "DJ Booth", hint: "One person controls the energy" },
    { word: "Saxophone", hint: "Smooth and late at night" },
    { word: "Ballet", hint: "Pain disguised as grace" },
    { word: "Opera", hint: "Emotions too large for speaking" },
    { word: "Headliner", hint: "What everyone came for" },
    { word: "Encore", hint: "Pretending it's over" },
    { word: "Music Festival", hint: "Mud, noise, and memories" },
    { word: "Jukebox", hint: "Nostalgia for a coin" },
    { word: "Rap Battle", hint: "Words weaponized on the spot" },
    { word: "Harmonica", hint: "Small enough to carry a feeling" },
    { word: "Choir", hint: "Many voices, one sound" },
    { word: "Mosh Pit", hint: "Chaos with consent" },
    { word: "Lullaby", hint: "The last thing heard before silence" },
    { word: "Autotune", hint: "Perfection that no one asked for" },
    { word: "Backstage Pass", hint: "Behind the curtain, by invitation" },
    { word: "Air Guitar", hint: "Passion without the instrument" },
    { word: "Spotlight", hint: "Nowhere to hide" },
    { word: "Boombox", hint: "Loud and unapologetic" },
    { word: "Ukulele", hint: "Happiness in four strings" },
    { word: "Remix", hint: "Familiar, but not quite" },
    { word: "Slow Dance", hint: "Time measured in heartbeats" },
    { word: "Tambourine", hint: "Shaking at the edges" },
    { word: "Waltz", hint: "Three beats, two people, one floor" },
    { word: "Kazoo", hint: "Ridiculous and impossible to ignore" },
    { word: "Fireworks", hint: "Beautiful because it's brief" },
    { word: "Stand-Up Comedy", hint: "Alone, hoping for a reaction" },
    { word: "Conga Line", hint: "Following blindly and loving it" },
    { word: "Beat Drop", hint: "The silence right before everything" },
    { word: "Violin", hint: "Can break your heart without words" },
    { word: "Dance Floor", hint: "Judgment disappears here" },
    { word: "Trumpet", hint: "Announces itself before arriving" },
    { word: "Open Mic", hint: "Bravery with no safety net" },
    { word: "Playlist", hint: "A mood, organized" },
    { word: "Lip Sync", hint: "All performance, no voice" },
    { word: "Disco Ball", hint: "Scatters light everywhere" },
    { word: "Accordion", hint: "Breathing in and out" },
    { word: "Music Box", hint: "Tiny and haunting" },
    { word: "Subwoofer", hint: "Felt before it's heard" },
    { word: "Metronome", hint: "Perfect time, no soul" },
    { word: "Maracas", hint: "Shake to participate" },
    { word: "Stage Dive", hint: "Trust fall at maximum volume" }
  ],

  "Around the House": [
    { word: "Junk Drawer", hint: "Chaos with a handle" },
    { word: "Couch Cushion", hint: "Swallows things whole" },
    { word: "Shower", hint: "Where the best ideas come" },
    { word: "Refrigerator", hint: "Opened out of boredom" },
    { word: "Doormat", hint: "First impression, constantly stepped on" },
    { word: "Smoke Detector", hint: "Screams at your cooking" },
    { word: "Garage", hint: "Stores everything except the car" },
    { word: "Wi-Fi Router", hint: "Invisible lifeline" },
    { word: "Laundry Basket", hint: "Always overflowing" },
    { word: "Kitchen Timer", hint: "Small panic when it goes off" },
    { word: "Ceiling Fan", hint: "Going nowhere, making a difference" },
    { word: "Recliner", hint: "Where ambition goes to rest" },
    { word: "Toaster", hint: "Patience measured in golden brown" },
    { word: "Bathroom Mirror", hint: "The first face you see" },
    { word: "Front Porch", hint: "Between inside and outside" },
    { word: "Vacuum Cleaner", hint: "Loud and demanding" },
    { word: "Dishwasher", hint: "Trusted with the aftermath" },
    { word: "Closet", hint: "Secrets behind a door" },
    { word: "Mailbox", hint: "Mostly disappointment, occasionally joy" },
    { word: "Nightstand", hint: "Closest companion while sleeping" },
    { word: "Thermostat", hint: "One degree starts a war" },
    { word: "Garage Door", hint: "The slow reveal" },
    { word: "Toilet", hint: "No one talks about it, everyone needs it" },
    { word: "Pantry", hint: "Options that never satisfy" },
    { word: "Patio", hint: "Inside, but make it outside" },
    { word: "Window Blinds", hint: "Control how much world gets in" },
    { word: "Coffee Table", hint: "Feet and magazines" },
    { word: "Dryer", hint: "Eats socks in secret" },
    { word: "Doorknob", hint: "Touched by everyone, noticed by none" },
    { word: "Light Switch", hint: "Tiny decision, big change" },
    { word: "Staircase", hint: "Taken for granted until it's not there" },
    { word: "Basement", hint: "Everything you're avoiding is down there" },
    { word: "Spice Rack", hint: "Ambition collecting dust" },
    { word: "Throw Blanket", hint: "Comfort within arm's reach" },
    { word: "Coat Rack", hint: "First thing off, last thing on" },
    { word: "Bird Feeder", hint: "Charity for strangers with wings" },
    { word: "Garden Hose", hint: "Tangles itself when you're not looking" },
    { word: "Bookshelf", hint: "Organized identity on display" },
    { word: "Bathrobe", hint: "Too comfortable to take off" },
    { word: "Ice Maker", hint: "Loud at 3 AM" },
    { word: "Peephole", hint: "Seeing without being seen" },
    { word: "Soap Dispenser", hint: "One push and you're clean" },
    { word: "Fireplace", hint: "Warmth that demands attention" },
    { word: "Picture Frame", hint: "Frozen smiles on the wall" },
    { word: "Garbage Disposal", hint: "Angry and brief" },
    { word: "Kitchen Sponge", hint: "Absorbs everything" },
    { word: "House Key", hint: "Small metal, big trust" },
    { word: "Ceiling", hint: "Stared at when thinking" }
  ]
};

module.exports = WORDS;
