// Word bank organized by category
// Each word has a vague hint for the imposter

const WORDS = {
  "Animals": [
    { word: "Tiger", hint: "Something you'd see at a zoo" },
    { word: "Penguin", hint: "Lives where it's very cold" },
    { word: "Dolphin", hint: "A smart creature in the ocean" },
    { word: "Eagle", hint: "Soars high above the mountains" },
    { word: "Elephant", hint: "One of the biggest land animals" },
    { word: "Chameleon", hint: "Known for changing appearance" },
    { word: "Octopus", hint: "Has more limbs than most" },
    { word: "Kangaroo", hint: "Gets around by bouncing" },
    { word: "Giraffe", hint: "Stands taller than the rest" },
    { word: "Parrot", hint: "Can mimic human speech" },
    { word: "Shark", hint: "The ocean's top predator" },
    { word: "Butterfly", hint: "Goes through a big transformation" },
    { word: "Panda", hint: "A beloved black and white animal" },
    { word: "Flamingo", hint: "Known for standing on one leg" },
    { word: "Sloth", hint: "The world's slowest creature" },
    { word: "Cheetah", hint: "The fastest thing on land" },
    { word: "Jellyfish", hint: "Floats and stings in the sea" },
    { word: "Peacock", hint: "Shows off colorful feathers" },
    { word: "Gorilla", hint: "Our closest relative in the jungle" },
    { word: "Seahorse", hint: "A tiny ocean creature with a curly tail" },
    { word: "Koala", hint: "Sleeps in trees most of the day" },
    { word: "Bat", hint: "The only flying mammal" },
    { word: "Crocodile", hint: "Lurks near riverbanks" },
    { word: "Wolf", hint: "Howls at the moon" },
    { word: "Owl", hint: "A wise bird of the night" },
    { word: "Hedgehog", hint: "Small and covered in spikes" },
    { word: "Whale", hint: "The largest creature on earth" },
    { word: "Fox", hint: "Cunning and red-furred" },
    { word: "Turtle", hint: "Carries its home on its back" },
    { word: "Hamster", hint: "A tiny pet that runs on a wheel" }
  ],

  "Food & Drinks": [
    { word: "Pizza", hint: "A popular Friday night dinner" },
    { word: "Sushi", hint: "A Japanese delicacy with rice" },
    { word: "Tacos", hint: "Wrapped in a shell or tortilla" },
    { word: "Ice Cream", hint: "A frozen treat for hot days" },
    { word: "Pancakes", hint: "A breakfast stack" },
    { word: "Chocolate", hint: "The world's favorite sweet" },
    { word: "Avocado", hint: "Trendy green fruit on toast" },
    { word: "Popcorn", hint: "A movie theater essential" },
    { word: "Pasta", hint: "An Italian staple with sauce" },
    { word: "Burger", hint: "A classic American sandwich" },
    { word: "Watermelon", hint: "A big juicy summer fruit" },
    { word: "Coffee", hint: "Millions need this to wake up" },
    { word: "Nachos", hint: "Chips covered in cheese and toppings" },
    { word: "Donut", hint: "A ring-shaped breakfast treat" },
    { word: "Ramen", hint: "A hot bowl of noodle soup" },
    { word: "Smoothie", hint: "A blended fruity drink" },
    { word: "Pretzel", hint: "A twisted salty snack" },
    { word: "Waffles", hint: "Grid-patterned breakfast food" },
    { word: "Mango", hint: "A tropical yellow-orange fruit" },
    { word: "Steak", hint: "A thick cut of grilled meat" },
    { word: "Lemonade", hint: "A refreshing citrus drink" },
    { word: "Mac and Cheese", hint: "Comfort food with noodles" },
    { word: "Boba Tea", hint: "A drink with chewy balls at the bottom" },
    { word: "French Fries", hint: "Golden sticks served with ketchup" },
    { word: "Milkshake", hint: "A thick, creamy drink you sip through a straw" },
    { word: "Croissant", hint: "A flaky French pastry" },
    { word: "Hot Dog", hint: "A ballpark classic" },
    { word: "Cheesecake", hint: "A rich, creamy dessert" },
    { word: "Fried Chicken", hint: "Crispy, crunchy, and golden" },
    { word: "Cereal", hint: "Breakfast in a bowl with milk" }
  ],

  "Places": [
    { word: "Beach", hint: "Where land meets the ocean" },
    { word: "Library", hint: "A quiet place full of books" },
    { word: "Hospital", hint: "Where you go when you're hurt" },
    { word: "Airport", hint: "Where planes take off and land" },
    { word: "Casino", hint: "A place to test your luck" },
    { word: "Museum", hint: "Full of history and art" },
    { word: "Gym", hint: "Where people go to exercise" },
    { word: "Mall", hint: "A big building full of shops" },
    { word: "Theme Park", hint: "Roller coasters and cotton candy" },
    { word: "Movie Theater", hint: "Big screen in a dark room" },
    { word: "Restaurant", hint: "Where someone cooks for you" },
    { word: "Camping", hint: "Sleeping under the stars" },
    { word: "School", hint: "Where kids learn every weekday" },
    { word: "Zoo", hint: "Animals behind fences" },
    { word: "Stadium", hint: "Tens of thousands cheer here" },
    { word: "Aquarium", hint: "Fish tanks everywhere you look" },
    { word: "Cruise Ship", hint: "A floating hotel on the ocean" },
    { word: "Farm", hint: "Barns, tractors, and livestock" },
    { word: "Spa", hint: "A place to relax and unwind" },
    { word: "Ski Resort", hint: "Snow, slopes, and hot cocoa" },
    { word: "Bowling Alley", hint: "Roll a heavy ball at pins" },
    { word: "Laundromat", hint: "Where you wash your clothes" },
    { word: "Barbershop", hint: "Where you get a fresh haircut" },
    { word: "Gas Station", hint: "Where cars refuel" },
    { word: "Cemetery", hint: "A quiet resting place" },
    { word: "Lighthouse", hint: "Guides ships at night" },
    { word: "Treehouse", hint: "A hideout up in the branches" },
    { word: "Rooftop", hint: "The top of a tall building" },
    { word: "Subway", hint: "Underground transportation" },
    { word: "Church", hint: "A place of worship" }
  ],

  "Jobs & Professions": [
    { word: "Firefighter", hint: "Runs toward danger, not away" },
    { word: "Astronaut", hint: "Works far above the Earth" },
    { word: "Chef", hint: "Creates meals for a living" },
    { word: "Detective", hint: "Solves mysteries and crimes" },
    { word: "Pilot", hint: "Flies through the sky" },
    { word: "Dentist", hint: "Looks inside your mouth" },
    { word: "Lifeguard", hint: "Watches over swimmers" },
    { word: "DJ", hint: "Controls the music at parties" },
    { word: "Surgeon", hint: "Operates in a hospital" },
    { word: "Magician", hint: "Makes things appear and disappear" },
    { word: "Plumber", hint: "Fixes things that flow" },
    { word: "Veterinarian", hint: "A doctor for animals" },
    { word: "Barista", hint: "Makes your morning drink" },
    { word: "Photographer", hint: "Captures moments forever" },
    { word: "Electrician", hint: "Works with wires and power" },
    { word: "Tattoo Artist", hint: "Draws permanently on skin" },
    { word: "Zookeeper", hint: "Takes care of wild animals" },
    { word: "Coach", hint: "Trains athletes to win" },
    { word: "Librarian", hint: "Knows where every book is" },
    { word: "Mailman", hint: "Delivers packages to your door" },
    { word: "Archaeologist", hint: "Digs up the past" },
    { word: "Weatherman", hint: "Predicts rain or shine" },
    { word: "Florist", hint: "Arranges beautiful blooms" },
    { word: "Bus Driver", hint: "Takes people on a route" },
    { word: "Clown", hint: "Makes kids laugh at parties" },
    { word: "Blacksmith", hint: "Forges metal with fire" },
    { word: "Farmer", hint: "Grows crops and raises animals" },
    { word: "Journalist", hint: "Writes the news" },
    { word: "Mime", hint: "Performs without speaking" },
    { word: "Stunt Double", hint: "Does dangerous things for movies" }
  ],

  "Movies & TV": [
    { word: "Star Wars", hint: "An epic space saga" },
    { word: "The Lion King", hint: "A royal animal story" },
    { word: "Harry Potter", hint: "A magical school adventure" },
    { word: "The Office", hint: "A mockumentary about work life" },
    { word: "Titanic", hint: "A doomed ship and a love story" },
    { word: "Stranger Things", hint: "Kids vs supernatural in the 80s" },
    { word: "Finding Nemo", hint: "A dad searches the ocean" },
    { word: "Friends", hint: "Six people hanging out in NYC" },
    { word: "Jurassic Park", hint: "Dinosaurs come back to life" },
    { word: "Breaking Bad", hint: "A teacher turns to crime" },
    { word: "Frozen", hint: "A cold kingdom and two sisters" },
    { word: "The Avengers", hint: "Superheroes team up" },
    { word: "Shrek", hint: "An ogre's fairy tale" },
    { word: "Game of Thrones", hint: "A battle for the throne" },
    { word: "Toy Story", hint: "When you leave, your toys come alive" },
    { word: "Batman", hint: "A dark hero with no powers" },
    { word: "SpongeBob", hint: "Lives in a pineapple" },
    { word: "The Matrix", hint: "Reality isn't what it seems" },
    { word: "Jaws", hint: "Stay out of the water" },
    { word: "Indiana Jones", hint: "An adventurer with a whip and hat" },
    { word: "Squid Game", hint: "Deadly children's games" },
    { word: "Ghostbusters", hint: "Who ya gonna call?" },
    { word: "The Simpsons", hint: "A yellow animated family" },
    { word: "Rocky", hint: "An underdog boxer" },
    { word: "Up", hint: "A house that floats away" },
    { word: "Twilight", hint: "Vampires and romance" },
    { word: "Scooby-Doo", hint: "A mystery-solving dog" },
    { word: "Jeopardy", hint: "Answer in the form of a question" },
    { word: "Willy Wonka", hint: "A magical candy factory" },
    { word: "The Walking Dead", hint: "Surviving after the apocalypse" }
  ],

  "Sports & Hobbies": [
    { word: "Basketball", hint: "Shoot it through the hoop" },
    { word: "Surfing", hint: "Riding waves on a board" },
    { word: "Chess", hint: "A strategic board game with kings" },
    { word: "Yoga", hint: "Stretch, breathe, and hold" },
    { word: "Skateboarding", hint: "Four wheels and a deck" },
    { word: "Fishing", hint: "Patience by the water" },
    { word: "Boxing", hint: "Fighting with gloves in a ring" },
    { word: "Photography", hint: "Capturing the world through a lens" },
    { word: "Rock Climbing", hint: "Scaling vertical surfaces" },
    { word: "Karate", hint: "A martial art with belts" },
    { word: "Bowling", hint: "Roll a ball to knock things down" },
    { word: "Golf", hint: "Hit a tiny ball into a hole" },
    { word: "Paintball", hint: "A colorful battle with friends" },
    { word: "Archery", hint: "Aim for the bullseye" },
    { word: "Tennis", hint: "Back and forth over a net" },
    { word: "Snowboarding", hint: "Sliding sideways down a mountain" },
    { word: "Poker", hint: "A card game about bluffing" },
    { word: "Scuba Diving", hint: "Exploring underwater with a tank" },
    { word: "Volleyball", hint: "Hit it over the net on the beach" },
    { word: "Ice Skating", hint: "Gliding on a frozen surface" },
    { word: "Pottery", hint: "Shaping clay with your hands" },
    { word: "Fencing", hint: "A sword sport with masks" },
    { word: "Darts", hint: "Throwing sharp things at a board" },
    { word: "Table Tennis", hint: "Ping pong back and forth" },
    { word: "Hiking", hint: "Walking up mountains for fun" },
    { word: "Wrestling", hint: "Grappling on a mat" },
    { word: "Gardening", hint: "Growing plants in your yard" },
    { word: "Horse Riding", hint: "Sitting on a galloping animal" },
    { word: "Swimming", hint: "Moving through water" },
    { word: "Magic Tricks", hint: "Illusions that amaze an audience" }
  ],

  "Brands & Products": [
    { word: "Nike", hint: "Just do it" },
    { word: "iPhone", hint: "A device billions carry daily" },
    { word: "Netflix", hint: "Binge-watching for hours" },
    { word: "Coca-Cola", hint: "The world's most famous drink" },
    { word: "LEGO", hint: "Tiny bricks that build anything" },
    { word: "McDonald's", hint: "Golden arches everywhere" },
    { word: "Tesla", hint: "Electric cars and a famous CEO" },
    { word: "Disney", hint: "Where dreams come true" },
    { word: "Amazon", hint: "Everything delivered to your door" },
    { word: "PlayStation", hint: "A popular gaming console" },
    { word: "Google", hint: "The answer to every question" },
    { word: "Starbucks", hint: "A coffee chain on every corner" },
    { word: "Instagram", hint: "Sharing photos with filters" },
    { word: "IKEA", hint: "Flat-pack furniture you assemble" },
    { word: "Uber", hint: "A ride from your phone" },
    { word: "YouTube", hint: "Watch any video ever made" },
    { word: "Nintendo", hint: "Home of Mario and Zelda" },
    { word: "Spotify", hint: "Stream any song you want" },
    { word: "Oreo", hint: "Twist, lick, and dunk" },
    { word: "TikTok", hint: "Short videos that go viral" },
    { word: "Airbnb", hint: "Stay in someone else's home" },
    { word: "Red Bull", hint: "It gives you wings" },
    { word: "Adidas", hint: "Three stripes on everything" },
    { word: "Minecraft", hint: "A blocky world you can build" },
    { word: "Doritos", hint: "Triangular flavored chips" },
    { word: "Monopoly", hint: "A board game about real estate" },
    { word: "Kleenex", hint: "What you reach for when you sneeze" },
    { word: "Gatorade", hint: "A sports drink for athletes" },
    { word: "Hot Wheels", hint: "Tiny toy cars on orange tracks" },
    { word: "Nutella", hint: "Chocolate spread on everything" }
  ],

  "Everyday Things": [
    { word: "Umbrella", hint: "Protects you from the sky" },
    { word: "Microwave", hint: "Heats food up in seconds" },
    { word: "Sunglasses", hint: "Worn on your face on bright days" },
    { word: "Alarm Clock", hint: "The most annoying sound in the morning" },
    { word: "Backpack", hint: "Carries your stuff on your back" },
    { word: "Elevator", hint: "Takes you up without stairs" },
    { word: "Remote Control", hint: "Always lost between the couch cushions" },
    { word: "Toothbrush", hint: "Used twice a day for hygiene" },
    { word: "Pillow", hint: "Your head rests on it at night" },
    { word: "Wallet", hint: "Holds your money and cards" },
    { word: "Mirror", hint: "Shows you yourself" },
    { word: "Candle", hint: "Light and scent from a wick" },
    { word: "Ladder", hint: "Step by step, you go higher" },
    { word: "Headphones", hint: "Music goes straight to your ears" },
    { word: "Battery", hint: "Stores power for devices" },
    { word: "Scissors", hint: "Two blades that cut" },
    { word: "Doorbell", hint: "Ding dong, someone's here" },
    { word: "Trampoline", hint: "Bounce up and down on it" },
    { word: "Blender", hint: "Spins and mixes things fast" },
    { word: "Zipper", hint: "Opens and closes your jacket" },
    { word: "Flashlight", hint: "A beam in the dark" },
    { word: "Stamp", hint: "Needed to mail a letter" },
    { word: "Hammock", hint: "Swings between two trees" },
    { word: "Thermos", hint: "Keeps drinks hot or cold" },
    { word: "Magnifying Glass", hint: "Makes small things look big" },
    { word: "Compass", hint: "Always points the same direction" },
    { word: "Lunchbox", hint: "Carries your midday meal" },
    { word: "Suitcase", hint: "Packed before a trip" },
    { word: "Rubber Duck", hint: "A bath time companion" },
    { word: "Post-it Note", hint: "A sticky little reminder" }
  ]
};

module.exports = WORDS;
